#!/bin/bash
echo '#ifdef __cplusplus' > /tmp/newfile
echo 'extern "C" {' >>/tmp/newfile
echo '#endif' >> /tmp/newfile

cat ./yacc.h >> /tmp/newfile

echo '#ifdef __cplusplus' >>  /tmp/newfile
echo '}' >> /tmp/newfile
echo '#endif' >> /tmp/newfile
cp /tmp/newfile ./yacc.h
